"use client";

import { useState } from "react";
import { Badge, Box, Button, Collapse, Group, Paper, SimpleGrid, Stack, Text, Title } from "@mantine/core";
import { IconChevronDown, IconChevronUp } from "@tabler/icons-react";

type ConceptData = {
  mainTheme?: unknown;
  premise?: unknown;
  readerPromise?: unknown;
  emotionalEngine?: unknown;
  genreFit?: unknown;
  targetAudienceFit?: unknown;
  creationThesis?: unknown;
  suggestedStructure?: unknown;
  coreQuestions?: unknown[];
  differentiators?: unknown[];
  majorRisks?: unknown[];
};

type CreationProject = {
  working_title?: string | null;
  genre?: string | null;
  target_audience?: string | null;
  language?: string | null;
  target_pages?: number | null;
  tone?: string | null;
};

function toDisplayString(value: unknown): string {
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return value.map(toDisplayString).join(", ");
  if (value && typeof value === "object") {
    return Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${k}: ${toDisplayString(v)}`)
      .join(" · ");
  }
  return "";
}

function Field({ label, value }: { label: string; value: unknown }) {
  const display = toDisplayString(value);
  if (!display) return null;
  return (
    <Box>
      <Text size="xs" fw={700} tt="uppercase" c="dimmed" mb={2}>
        {label}
      </Text>
      <Text size="sm">{display}</Text>
    </Box>
  );
}

function ListField({ label, items }: { label: string; items: string[] }) {
  if (!items.length) return null;
  return (
    <Box>
      <Text size="xs" fw={700} tt="uppercase" c="dimmed" mb={4}>
        {label}
      </Text>
      <Stack gap={2}>
        {items.map((item, i) => (
          <Text size="sm" key={i}>
            · {item}
          </Text>
        ))}
      </Stack>
    </Box>
  );
}

export function BookConceptPanel({
  creationProject,
  concept,
  seedLocked,
  seedSource,
}: {
  creationProject: CreationProject;
  concept: ConceptData;
  seedLocked?: boolean;
  seedSource?: "creation-plan" | "book-metadata";
}) {
  const [open, setOpen] = useState(false);

  const coreQuestions = Array.isArray(concept.coreQuestions) ? concept.coreQuestions.map(toDisplayString).filter(Boolean) : [];
  const differentiators = Array.isArray(concept.differentiators) ? concept.differentiators.map(toDisplayString).filter(Boolean) : [];
  const majorRisks = Array.isArray(concept.majorRisks) ? concept.majorRisks.map(toDisplayString).filter(Boolean) : [];

  return (
    <Paper withBorder radius="md" p="xl" bg="#f0f4ff" mb="xl">
      <Group justify="space-between" align="flex-start">
        <div>
          <Title order={3}>Book Concept</Title>
          <Text c="dimmed" size="sm">
            Generated by BookForge Creator · approved concept used for architecture and draft generation
          </Text>
        </div>
        <Group gap="md" align="center">
          <Group gap="xs">
            {seedLocked && (
              <Badge color="green" variant="light">Seed locked</Badge>
            )}
            {seedLocked && seedSource === "book-metadata" && (
              <Badge color="blue" variant="light">Loaded from saved seed snapshot</Badge>
            )}
            {creationProject.genre && <Badge color="teal" variant="light">{creationProject.genre}</Badge>}
            {creationProject.language && creationProject.language !== "English" && (
              <Badge color="indigo" variant="light">{creationProject.language}</Badge>
            )}
            {creationProject.target_pages && (
              <Badge color="gray" variant="light">{creationProject.target_pages} pp target</Badge>
            )}
          </Group>
          <Button
            size="sm"
            variant="filled"
            color="grape"
            rightSection={open ? <IconChevronUp size={14} /> : <IconChevronDown size={14} />}
            onClick={() => setOpen((o) => !o)}
          >
            {open ? "Hide Concept" : "Review Concept"}
          </Button>
        </Group>
      </Group>

      <Collapse expanded={open}>
        <SimpleGrid cols={{ base: 1, md: 2 }} spacing="lg" mt="md">
          <Stack gap="md">
            <Field label="Main Theme" value={concept.mainTheme} />
            <Field label="Premise" value={concept.premise} />
            <Field label="Reader Promise" value={concept.readerPromise} />
            <Field label="Emotional Engine" value={concept.emotionalEngine} />
            <Field label="Creation Thesis" value={concept.creationThesis} />
          </Stack>
          <Stack gap="md">
            <Field label="Genre Fit" value={concept.genreFit} />
            <Field label="Audience Fit" value={concept.targetAudienceFit} />
            <Field label="Suggested Structure" value={concept.suggestedStructure} />
            {creationProject.tone && <Field label="Tone" value={creationProject.tone} />}
            <ListField label="Core Questions" items={coreQuestions} />
            <ListField label="Differentiators" items={differentiators} />
            {majorRisks.length > 0 && <ListField label="Author Risks to Watch" items={majorRisks} />}
          </Stack>
        </SimpleGrid>
      </Collapse>
    </Paper>
  );
}
